In [20]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [25]:
cust = pd.read_csv(r'C:\Users\leeji\Desktop\study_csv\csv\sc_cust_info_txn_v1.5.csv')
cust

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [26]:
gender_group = cust.groupby("sex_type")
gender_group

In [27]:
gender_group.groups

{'F': [0, 2, 3, 5, 7, 9, 12, 13, 14, 16, 17, 19, 20, 21, 24, 25, 26, 40, 41, 43, 46, 47, 49, 51, 52, 55, 65, 69, 73, 75, 77, 79, 80, 81, 82, 85, 86, 90, 91, 93, 94, 95, 101, 105, 106, 111, 112, 116, 119, 120, 121, 127, 130, 131, 134, 135, 136, 137, 138, 142, 143, 147, 148, 149, 151, 152, 155, 156, 157, 159, 163, 164, 166, 167, 169, 173, 174, 176, 177, 181, 184, 190, 191, 193, 195, 197, 205, 206, 208, 210, 211, 213, 215, 216, 218, 221, 225, 230, 234, 235, ...], 'M': [4, 6, 8, 11, 15, 18, 22, 23, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 42, 44, 45, 48, 50, 53, 54, 56, 57, 58, 59, 60, 61, 63, 64, 67, 68, 70, 74, 76, 78, 84, 87, 88, 89, 96, 97, 98, 99, 100, 103, 104, 107, 108, 109, 110, 113, 115, 117, 122, 123, 124, 125, 126, 128, 132, 133, 139, 140, 141, 144, 145, 146, 150, 153, 154, 158, 160, 161, 162, 168, 170, 171, 172, 175, 178, 179, 180, 183, 185, 186, 187, 188, 189, 192, 194, 198, 199, 200, 201, ...], '_': [1, 10, 35, 62, 66, 71, 72, 83, 92, 102, 114, 118, 129, 165, 182, 196, 228, 232, 243, 288, 314, 317, 324, 393, 394, 451, 489, 496, 501, 502, 573, 611, 629, 658, 667, 669, 676, 683, 690, 701, 708, 717, 739, 751, 758, 773, 792, 816, 820, 821, 836, 851, 864, 895, 910, 935, 937, 942, 943, 946, 950, 971, 986, 991, 992, 1005, 1008, 1011, 1012, 1015, 1021, 1023, 1027, 1056, 1058, 1062, 1077, 1088, 1102, 1108, 1147, 1171, 1174, 1185, 1196, 1209, 1214, 1215, 1237, 1240, 1241, 1273, 1281, 1284, 1296, 1302, 1314, 1330, 1360, 1363, ...]}

In [28]:
gender_group.count()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
sex_type,,,,,,,,,,,,,,
F,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251
M,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998
_,681,681,681,681,681,681,681,681,681,681,681,681,681,681

In [32]:
gender_group.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [33]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   base_ym             9930 non-null   int64
 1   dpro_tgt_perd_val   9930 non-null   int64
 2   cust_ctg_type       9930 non-null   int64
 3   cust_class          9930 non-null   object
 4   sex_type            9930 non-null   object
 5   age                 9930 non-null   object
 6   efct_svc_count      9930 non-null   int64
 7   dt_stop_yn          9930 non-null   object
 8   npay_yn             9930 non-null   object
 9   r3m_avg_bill_amt    9930 non-null   float64
 10  r3m_A_avg_arpu_amt  9930 non-null   float64
 11  r3m_B_avg_arpu_amt  9930 non-null   float64
 12  r6m_A_avg_arpu_amt  9930 non-null   float64
 13  r6m_B_avg_arpu_amt  9930 non-null   float64
 14  termination_yn      9930 non-null   object
dtypes: float64(5), int64(4), object(6)
memory usage: 1.1+ MB

In [34]:
cust.select_dtypes(['int64', 'float64'])

,base_ym,dpro_tgt_perd_val,cust_ctg_type,efct_svc_count,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt
0,202006,20200630,10001,0,2640.0000,792.000000,1584.0000,0.0,0.0000
1,202006,20200630,10001,1,300.0000,90.000000,180.0000,0.0,0.0000
2,202006,20200630,10001,1,16840.0000,2526.000000,6983.0000,0.0,6981.0000
3,202006,20200630,10001,1,15544.7334,2331.710010,6750.4666,0.0,6508.8000
4,202006,20200630,10001,1,4700.0000,0.000000,4502.0000,0.0,4507.7000
...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,1,1296.0999,194.414985,643.1001,0.0,852.5499
9926,202006,20200630,10001,1,13799.6666,2069.949990,10605.9266,0.0,10603.9266
9927,202006,20200630,10005,1,1396.2000,1206.000000,0.0000,1212.0,0.0000
9928,202006,20200630,10001,0,3140.0000,942.000000,1884.0000,0.0,0.0000
9929,202006,20200630,10001,1,2436.9000,365.535000,1839.9000,0.0,1919.7999

In [35]:
col = cust.select_dtypes(['int64', 'float64']).columns
col

Index(['base_ym', 'dpro_tgt_perd_val', 'cust_ctg_type', 'efct_svc_count',
       'r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt', 'r3m_B_avg_arpu_amt',
       'r6m_A_avg_arpu_amt', 'r6m_B_avg_arpu_amt'],
      dtype='object')

In [36]:
gender_group[['r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']].mean()

          r3m_avg_bill_amt  r3m_A_avg_arpu_amt
sex_type
F              9580.926307         1570.372299
M              9839.707339         1778.988878
_             40297.790077         4809.827390

In [37]:
gender_group[col].mean()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,efct_svc_count,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt
sex_type,,,,,,,,,
F,202006.0,20200630.0,10001.001882,1.098800,9580.926307,1570.372299,5283.876950,452.780488,4961.455810
M,202006.0,20200630.0,10001.004802,1.204882,9839.707339,1778.988878,5342.748791,641.426866,4851.027884
_,202006.0,20200630.0,10006.389134,6.462555,40297.790077,4809.827390,21057.412985,4854.788244,864.386867

In [38]:
gender_group.max()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
sex_type,,,,,,,,,,,,,,
F,202006,20200630,10005,_,_,9,Y,Y,7.979563e+04,5.500240e+04,5.710153e+04,2.302815e+04,48787.2333,Y
M,202006,20200630,10005,_,_,14,Y,Y,1.447397e+05,1.315815e+05,6.583656e+04,2.749282e+04,64947.0920,Y
_,202006,20200630,10010,_,_,905,Y,Y,1.281568e+07,1.188998e+06,7.689409e+06,1.208498e+06,18796.6266,Y

In [39]:
gender_group.max()[['r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']]

          r3m_avg_bill_amt  r3m_A_avg_arpu_amt
sex_type
F             7.979563e+04        5.500240e+04
M             1.447397e+05        1.315815e+05
_             1.281568e+07        1.188998e+06

In [40]:
gender_group.mean()[['r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']]

TypeError: agg function failed [how->mean,dtype->object]

In [41]:
gender_group[['r3m_avg_bill_amt']].mean()

          r3m_avg_bill_amt
sex_type
F              9580.926307
M              9839.707339
_             40297.790077

In [42]:
cust.groupby('sex_type')[['r3m_avg_bill_amt']].mean()

          r3m_avg_bill_amt
sex_type
F              9580.926307
M              9839.707339
_             40297.790077

In [43]:
cust.groupby(['cust_class', 'sex_type'])[['r3m_avg_bill_amt']].mean()

                     r3m_avg_bill_amt
cust_class sex_type
C          F              3804.342244
           M              3155.385796
           _              4719.075980
D          F              7848.842709
           M              7774.098954
           _              8419.764574
E          F             11257.301485
           M             11158.736812
           _             12208.980550
F          F             14913.105272
           M             15013.379957
           _             16231.437767
G          F             16538.595017
           M             16847.160637
           _             20180.014811
H          F             20154.938768
           M             21052.154088
_          F              4304.582332
           M              4728.388010
           _             65268.733884

In [44]:
cust.groupby(['sex_type', 'cust_class'])[['r3m_avg_bill_amt']].mean()

                     r3m_avg_bill_amt
sex_type cust_class
F        C                3804.342244
         D                7848.842709
         E               11257.301485
         F               14913.105272
         G               16538.595017
         H               20154.938768
         _                4304.582332
M        C                3155.385796
         D                7774.098954
         E               11158.736812
         F               15013.379957
         G               16847.160637
         H               21052.154088
         _                4728.388010
_        C                4719.075980
         D                8419.764574
         E               12208.980550
         F               16231.437767
         G               20180.014811
         _               65268.733884

In [45]:
multi_group = cust.groupby(['cust_class', 'sex_type'])
multi_group[['r3m_avg_bill_amt']].mean()

                     r3m_avg_bill_amt
cust_class sex_type
C          F              3804.342244
           M              3155.385796
           _              4719.075980
D          F              7848.842709
           M              7774.098954
           _              8419.764574
E          F             11257.301485
           M             11158.736812
           _             12208.980550
F          F             14913.105272
           M             15013.379957
           _             16231.437767
G          F             16538.595017
           M             16847.160637
           _             20180.014811
H          F             20154.938768
           M             21052.154088
_          F              4304.582332
           M              4728.388010
           _             65268.733884

In [46]:
cust.groupby(['cust_class', 'sex_type'])[['r3m_avg_bill_amt']].mean().loc[[("C", "M"), ("D", "M")]]

                     r3m_avg_bill_amt
cust_class sex_type
C          M              3155.385796
D          M              7774.098954

In [47]:
cust.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N

In [48]:
cust.set_index(['cust_class'])

,base_ym,dpro_tgt_perd_val,cust_ctg_type,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
cust_class,,,,,,,,,,,,,,
C,202006,20200630,10001,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
_,202006,20200630,10001,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
E,202006,20200630,10001,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
F,202006,20200630,10001,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
D,202006,20200630,10001,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,202006,20200630,10001,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
G,202006,20200630,10001,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
C,202006,20200630,10005,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
C,202006,20200630,10001,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
C,202006,20200630,10001,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [49]:
multi_cust = cust.set_index(['cust_class', 'sex_type'])
multi_cust

                     base_ym  dpro_tgt_perd_val  cust_ctg_type age  \
cust_class sex_type
C          F          202006           20200630          10001  28
_          _          202006           20200630          10001   _
E          F          202006           20200630          10001  24
F          F          202006           20200630          10001  32
D          M          202006           20200630          10001  18
...                      ...                ...            ...  ..
C          F          202006           20200630          10001  15
G          M          202006           20200630          10001  12
C          _          202006           20200630          10005   _
           F          202006           20200630          10001  40
           F          202006           20200630          10001  59

                     efct_svc_count dt_stop_yn npay_yn  r3m_avg_bill_amt  \
cust_class sex_type
C          F                      0          N       N         2640.0000
_          _                      1          N       N          300.0000
E          F                      1          N       N        16840.0000
F          F                      1          N       N        15544.7334
D          M                      1          N       N         4700.0000
...                             ...        ...     ...               ...
C          F                      1          N       Y         1296.0999
G          M                      1          N       N        13799.6666
C          _                      1          N       N         1396.2000
           F                      0          N       N         3140.0000
           F                      1          N       N         2436.9000

                     r3m_A_avg_arpu_amt  r3m_B_avg_arpu_amt  \
cust_class sex_type
C          F                 792.000000           1584.0000
_          _                  90.000000            180.0000
E          F                2526.000000           6983.0000
F          F                2331.710010           6750.4666
D          M                   0.000000           4502.0000
...                                 ...                 ...
C          F                 194.414985            643.1001
G          M                2069.949990          10605.9266
C          _                1206.000000              0.0000
           F                 942.000000           1884.0000
           F                 365.535000           1839.9000

                     r6m_A_avg_arpu_amt  r6m_B_avg_arpu_amt termination_yn
cust_class sex_type
C          F                        0.0              0.0000              Y
_          _                        0.0              0.0000              Y
E          F                        0.0           6981.0000              N
F          F                        0.0           6508.8000              N
D          M                        0.0           4507.7000              N
...                                 ...                 ...            ...
C          F                        0.0            852.5499              N
G          M                        0.0          10603.9266              N
C          _                     1212.0              0.0000              N
           F                        0.0              0.0000              Y
           F                        0.0           1919.7999              N

[9930 rows x 13 columns]

In [50]:
multi_cust.reset_index()

,cust_class,sex_type,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,C,F,202006,20200630,10001,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
1,_,_,202006,20200630,10001,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
2,E,F,202006,20200630,10001,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
3,F,F,202006,20200630,10001,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
4,D,M,202006,20200630,10001,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,C,F,202006,20200630,10001,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,G,M,202006,20200630,10001,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,C,_,202006,20200630,10005,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,C,F,202006,20200630,10001,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,C,F,202006,20200630,10001,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [51]:
multi_cust.head(3)

,,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
cust_class,sex_type,,,,,,,,,,,,,
C,F,202006,20200630,10001,28,0,N,N,2640.0,792.0,1584.0,0.0,0.0,Y
_,_,202006,20200630,10001,_,1,N,N,300.0,90.0,180.0,0.0,0.0,Y
E,F,202006,20200630,10001,24,1,N,N,16840.0,2526.0,6983.0,0.0,6981.0,N

In [52]:
multi_cust.groupby('cust_class').count().head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
cust_class,,,,,,,,,,,,,
C,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092
D,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250
E,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269
F,726,726,726,726,726,726,726,726,726,726,726,726,726
G,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051

In [53]:
multi_cust.groupby('sex_type').count()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
sex_type,,,,,,,,,,,,,
F,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251
M,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998
_,681,681,681,681,681,681,681,681,681,681,681,681,681

In [54]:
cust.set_index(['cust_class', 'sex_type']).groupby(['cust_class', 'sex_type']).count().head(9)

                     base_ym  dpro_tgt_perd_val  cust_ctg_type   age  \
cust_class sex_type
C          F             849                849            849   849
           M            1064               1064           1064  1064
           _             179                179            179   179
D          F            1097               1097           1097  1097
           M            1087               1087           1087  1087
           _              66                 66             66    66
E          F             639                639            639   639
           M             606                606            606   606
           _              24                 24             24    24

                     efct_svc_count  dt_stop_yn  npay_yn  r3m_avg_bill_amt  \
cust_class sex_type
C          F                    849         849      849               849
           M                   1064        1064     1064              1064
           _                    179         179      179               179
D          F                   1097        1097     1097              1097
           M                   1087        1087     1087              1087
           _                     66          66       66                66
E          F                    639         639      639               639
           M                    606         606      606               606
           _                     24          24       24                24

                     r3m_A_avg_arpu_amt  r3m_B_avg_arpu_amt  \
cust_class sex_type
C          F                        849                 849
           M                       1064                1064
           _                        179                 179
D          F                       1097                1097
           M                       1087                1087
           _                         66                  66
E          F                        639                 639
           M                        606                 606
           _                         24                  24

                     r6m_A_avg_arpu_amt  r6m_B_avg_arpu_amt  termination_yn
cust_class sex_type
C          F                        849                 849             849
           M                       1064                1064            1064
           _                        179                 179             179
D          F                       1097                1097            1097
           M                       1087                1087            1087
           _                         66                  66              66
E          F                        639                 639             639
           M                        606                 606             606
           _                         24                  24              24

In [55]:
cust.set_index(['cust_class', 'sex_type']).groupby(['cust_class', 'sex_type']).aggregate(['count']).head(9)

                    base_ym dpro_tgt_perd_val cust_ctg_type   age  \
                      count             count         count count
cust_class sex_type
C          F            849               849           849   849
           M           1064              1064          1064  1064
           _            179               179           179   179
D          F           1097              1097          1097  1097
           M           1087              1087          1087  1087
           _             66                66            66    66
E          F            639               639           639   639
           M            606               606           606   606
           _             24                24            24    24

                    efct_svc_count dt_stop_yn npay_yn r3m_avg_bill_amt  \
                             count      count   count            count
cust_class sex_type
C          F                   849        849     849              849
           M                  1064       1064    1064             1064
           _                   179        179     179              179
D          F                  1097       1097    1097             1097
           M                  1087       1087    1087             1087
           _                    66         66      66               66
E          F                   639        639     639              639
           M                   606        606     606              606
           _                    24         24      24               24

                    r3m_A_avg_arpu_amt r3m_B_avg_arpu_amt r6m_A_avg_arpu_amt  \
                                 count              count              count
cust_class sex_type
C          F                       849                849                849
           M                      1064               1064               1064
           _                       179                179                179
D          F                      1097               1097               1097
           M                      1087               1087               1087
           _                        66                 66                 66
E          F                       639                639                639
           M                       606                606                606
           _                        24                 24                 24

                    r6m_B_avg_arpu_amt termination_yn
                                 count          count
cust_class sex_type
C          F                       849            849
           M                      1064           1064
           _                       179            179
D          F                      1097           1097
           M                      1087           1087
           _                        66             66
E          F                       639            639
           M                       606            606
           _                        24             24

In [56]:
cust.set_index(['cust_class', 'sex_type']).groupby(['cust_class', 'sex_type']).aggregate(['min', 'max']).head(9)

                    base_ym         dpro_tgt_perd_val           cust_ctg_type  \
                        min     max               min       max           min
cust_class sex_type
C          F         202006  202006          20200630  20200630         10001
           M         202006  202006          20200630  20200630         10001
           _         202006  202006          20200630  20200630         10001
D          F         202006  202006          20200630  20200630         10001
           M         202006  202006          20200630  20200630         10001
           _         202006  202006          20200630  20200630         10005
E          F         202006  202006          20200630  20200630         10001
           M         202006  202006          20200630  20200630         10001
           _         202006  202006          20200630  20200630         10005

                           age     efct_svc_count      ... r3m_A_avg_arpu_amt  \
                       max min max            min max  ...                min
cust_class sex_type                                    ...
C          F         10005  10  99              0   3  ...                0.0
           M         10005  10  95              0   5  ...                0.0
           _         10005   _   _              0   5  ...               90.0
D          F         10005  10  91              0   6  ...                0.0
           M         10005  10   _              0   5  ...                0.0
           _         10005   _   _              0   5  ...              284.7
E          F         10001  12   _              0   6  ...                0.0
           M         10001  14  92              0   7  ...                0.0
           _         10005   _   _              0   5  ...              519.0

                                 r3m_B_avg_arpu_amt               \
                             max                min          max
cust_class sex_type
C          F          48101.6216                0.0  14434.01600
           M          14774.7336                0.0  13909.40000
           _          12389.3334                0.0  13760.71998
D          F          16653.6667                0.0  14382.00000
           M         131581.5333                0.0  19255.69998
           _          18686.9650                0.0  19397.80002
E          F          16373.3334                0.0  17532.89170
           M          37972.7998                0.0  43474.32550
           _           8696.0666                0.0   9865.06002

                    r6m_A_avg_arpu_amt             r6m_B_avg_arpu_amt  \
                                   min         max                min
cust_class sex_type
C          F                       0.0  10316.0334                0.0
           M                       0.0   9689.3332                0.0
           _                       0.0  19648.5002                0.0
D          F                       0.0   8964.5224                0.0
           M                       0.0  27492.8165                0.0
           _                       0.0  10242.7268                0.0
E          F                       0.0  13069.3334                0.0
           M                       0.0  13100.7334                0.0
           _                       0.0   8704.5000                0.0

                                termination_yn
                            max            min max
cust_class sex_type
C          F         14432.0160              N   Y
           M         14787.1166              N   Y
           _          8200.4640              N   Y
D          F         14467.3334              N   Y
           M         18133.6304              N   Y
           _             0.0000              N   Y
E          F         17306.4000              N   Y
           M         39802.3921              N   Y
           _             0.0000              N   Y

[9 rows x 26 columns]

In [57]:
sample = pd.DataFrame(
    {'고객ID': ['cust_1', 'cust_1', 'cust_1', 'cust_2', 'cust_2', 'cust_2', 'cust_3', 'cust_3', 'cust_3'],
     '상품코드': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
     '등급': ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
     '구매금액': [30, 10, 0, 40, 15, 30, 0, 0, 10],
     '나이': [15, 40, 33, 29, 6, 30, 54, 69, 38]
     }
)
sample

     고객ID 상품코드 등급  구매금액  나이
0  cust_1   p1  A    30  15
1  cust_1   p2  A    10  40
2  cust_1   p3  A     0  33
3  cust_2   p1  A    40  29
4  cust_2   p2  A    15   6
5  cust_2   p3  A    30  30
6  cust_3   p1  B     0  54
7  cust_3   p2  B     0  69
8  cust_3   p3  B    10  38

In [58]:
pd.pivot_table(data = sample[['고객ID', '구매금액', '나이']], index = '고객ID', aggfunc = 'mean')

             구매금액         나이
고객ID
cust_1  13.333333  29.333333
cust_2  28.333333  21.666667
cust_3   3.333333  53.666667

In [59]:
sample[['고객ID', '구매금액', '나이']].groupby('고객ID').mean()

             구매금액         나이
고객ID
cust_1  13.333333  29.333333
cust_2  28.333333  21.666667
cust_3   3.333333  53.666667

In [60]:
sample.pivot_table(index = '고객ID', columns = '상품코드', aggfunc = 'sum')

       구매금액          나이         등급
상품코드     p1  p2  p3  p1  p2  p3 p1 p2 p3
고객ID
cust_1   30  10   0  15  40  33  A  A  A
cust_2   40  15  30  29   6  30  A  A  A
cust_3    0   0  10  54  69  38  B  B  B

In [61]:
sample

     고객ID 상품코드 등급  구매금액  나이
0  cust_1   p1  A    30  15
1  cust_1   p2  A    10  40
2  cust_1   p3  A     0  33
3  cust_2   p1  A    40  29
4  cust_2   p2  A    15   6
5  cust_2   p3  A    30  30
6  cust_3   p1  B     0  54
7  cust_3   p2  B     0  69
8  cust_3   p3  B    10  38

In [63]:
pd.pivot_table(data = sample, index = "등급", columns = "상품코드", values = "구매금액", aggfunc = np.sum)

상품코드  p1  p2  p3
등급
A     70  25  30
B      0   0  10

In [65]:
pd.pivot_table(data = sample, index = "등급", columns = "상품코드", values = "구매금액", aggfunc = "max")

상품코드  p1  p2  p3
등급
A     40  15  30
B      0   0  10

In [68]:
df = pd.DataFrame({
    '지역': ['서울', '서울', '서울', '경기', '경기', '부산', '서울', '서울', '부산', '경기', '경기', '경기'],
    '요일': ['월', '화', '수', '월', '화', '월', '목', '금', '화', '수', '목', '금'],
    '강수량': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120],
    '강수확률': [80, 70, 60, 50, 20, 10, 30, 40, 20, 10, 30, 40]
})

In [69]:
df.head()

   지역 요일  강수량  강수확률
0  서울  월   10    80
1  서울  화   20    70
2  서울  수   30    60
3  경기  월   40    50
4  경기  화   50    20

In [70]:
new_df = df.set_index(['지역', '요일'])

In [72]:
new_df.head()

       강수량  강수확률
지역 요일
서울 월    10    80
   화    20    70
   수    30    60
경기 월    40    50
   화    50    20

In [77]:
new_df.unstack("지역")

      강수량              강수확률
지역     경기    부산    서울    경기    부산    서울
요일
금   120.0   NaN  80.0  40.0   NaN  40.0
목   110.0   NaN  70.0  30.0   NaN  30.0
수   100.0   NaN  30.0  10.0   NaN  60.0
월    40.0  60.0  10.0  50.0  10.0  80.0
화    50.0  90.0  20.0  20.0  20.0  70.0

In [78]:
new_df.head(6)

       강수량  강수확률
지역 요일
서울 월    10    80
   화    20    70
   수    30    60
경기 월    40    50
   화    50    20
부산 월    60    10

In [83]:
new_df.unstack(1)

      강수량                            강수확률
요일      금      목      수     월     화     금     목     수     월     화
지역
경기  120.0  110.0  100.0  40.0  50.0  40.0  30.0  10.0  50.0  20.0
부산    NaN    NaN    NaN  60.0  90.0   NaN   NaN   NaN  10.0  20.0
서울   80.0   70.0   30.0  10.0  20.0  40.0  30.0  60.0  80.0  70.0

In [89]:
new_df.stack(0)

지역  요일
서울  월   강수량      10
        강수확률     80
    화   강수량      20
        강수확률     70
    수   강수량      30
        강수확률     60
경기  월   강수량      40
        강수확률     50
    화   강수량      50
        강수확률     20
부산  월   강수량      60
        강수확률     10
서울  목   강수량      70
        강수확률     30
    금   강수량      80
        강수확률     40
부산  화   강수량      90
        강수확률     20
경기  수   강수량     100
        강수확률     10
    목   강수량     110
        강수확률     30
    금   강수량     120
        강수확률     40
dtype: int64

In [90]:
df = pd.DataFrame({
    '지점': ['A', 'A', 'B', 'B'],
    '상품': ['p1', 'p2', 'p1', 'p2'],
    'Q1': [112, 134, 156, 178],
    'Q2': [212, 234, 256, 278],
    'Q3': [312, 334, 356, 378],
    'Q4': [412, 434, 456, 478]
})

In [91]:
import pandas as pd

In [92]:
df = pd.DataFrame({
    '지점': ['A', 'A', 'B', 'B'],
    '상품': ['p1', 'p2', 'p1', 'p2'],
    'Q1': [112, 134, 156, 178],
    'Q2': [212, 234, 256, 278],
    'Q3': [312, 334, 356, 378],
    'Q4': [412, 434, 456, 478]
})

In [94]:
df

  지점  상품   Q1   Q2   Q3   Q4
0  A  p1  112  212  312  412
1  A  p2  134  234  334  434
2  B  p1  156  256  356  456
3  B  p2  178  278  378  478

In [95]:
df.head()

  지점  상품   Q1   Q2   Q3   Q4
0  A  p1  112  212  312  412
1  A  p2  134  234  334  434
2  B  p1  156  256  356  456
3  B  p2  178  278  378  478

In [96]:
df.tail()

  지점  상품   Q1   Q2   Q3   Q4
0  A  p1  112  212  312  412
1  A  p2  134  234  334  434
2  B  p1  156  256  356  456
3  B  p2  178  278  378  478

In [98]:
df.shape

(4, 6)

In [99]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [100]:
list(df.index)

[0, 1, 2, 3]

In [101]:
df.columns

Index(['지점', '상품', 'Q1', 'Q2', 'Q3', 'Q4'], dtype='object')

In [102]:
df.columns[-2:]

Index(['Q3', 'Q4'], dtype='object')

In [103]:
df.values

array([['A', 'p1', 112, 212, 312, 412],
       ['A', 'p2', 134, 234, 334, 434],
       ['B', 'p1', 156, 256, 356, 456],
       ['B', 'p2', 178, 278, 378, 478]], dtype=object)

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지점      4 non-null      object
 1   상품      4 non-null      object
 2   Q1      4 non-null      int64
 3   Q2      4 non-null      int64
 4   Q3      4 non-null      int64
 5   Q4      4 non-null      int64
dtypes: int64(4), object(2)
memory usage: 324.0+ bytes

In [105]:
df.drop('상품', axis=1).groupby('지점').mean()

       Q1     Q2     Q3     Q4
지점
A   123.0  223.0  323.0  423.0
B   167.0  267.0  367.0  467.0

In [106]:
df.drop('지점', axis = 1).groupby('상품').mean()

       Q1     Q2     Q3     Q4
상품
p1  134.0  234.0  334.0  434.0
p2  156.0  256.0  356.0  456.0

In [107]:
df.head(3)

  지점  상품   Q1   Q2   Q3   Q4
0  A  p1  112  212  312  412
1  A  p2  134  234  334  434
2  B  p1  156  256  356  456

In [108]:
pd.pivot_table(data = df, index = '지점', columns = '상품', values = "Q1", aggfunc = np.sum)

상품   p1   p2
지점
A   112  134
B   156  178

In [109]:
pd.pivot_table(data = df, index = '지점', columns = '상품', values = 'Q1', aggfunc = 'mean')

상품     p1     p2
지점
A   112.0  134.0
B   156.0  178.0

In [110]:
df1 = df.set_index('지점')

In [111]:
df1

    상품   Q1   Q2   Q3   Q4
지점
A   p1  112  212  312  412
A   p2  134  234  334  434
B   p1  156  256  356  456
B   p2  178  278  378  478

In [112]:
df1.reset_index()

  지점  상품   Q1   Q2   Q3   Q4
0  A  p1  112  212  312  412
1  A  p2  134  234  334  434
2  B  p1  156  256  356  456
3  B  p2  178  278  378  478

In [114]:
df2 = df.set_index(['지점', '상품'])

In [115]:
df2

        Q1   Q2   Q3   Q4
지점 상품
A  p1  112  212  312  412
   p2  134  234  334  434
B  p1  156  256  356  456
   p2  178  278  378  478

In [116]:
df2.unstack(1)

     Q1        Q2        Q3        Q4
상품   p1   p2   p1   p2   p1   p2   p1   p2
지점
A   112  134  212  234  312  334  412  434
B   156  178  256  278  356  378  456  478

In [117]:
df2.stack(0)

지점  상품
A   p1  Q1    112
        Q2    212
        Q3    312
        Q4    412
    p2  Q1    134
        Q2    234
        Q3    334
        Q4    434
B   p1  Q1    156
        Q2    256
        Q3    356
        Q4    456
    p2  Q1    178
        Q2    278
        Q3    378
        Q4    478
dtype: int64

In [121]:
df3 = df2.unstack('지점')

In [122]:
df3

     Q1        Q2        Q3        Q4
지점    A    B    A    B    A    B    A    B
상품
p1  112  156  212  256  312  356  412  456
p2  134  178  234  278  334  378  434  478

In [123]:
df3.stack('지점')

        Q1   Q2   Q3   Q4
상품 지점
p1 A   112  212  312  412
   B   156  256  356  456
p2 A   134  234  334  434
   B   178  278  378  478

In [124]:
import pandas as pd
import numpy as np

In [125]:
df1 = pd.DataFrame({'key1' : [0, 1, 2, 3, 4], 'values' : ['A', 'B', 'C', 'D', 'E']}, index = [0, 1, 2, 3, 4])
df2 = pd.DataFrame({'key1' : [3, 4, 5, 6, 7], 'values' : ['C', 'D', 'E', 'F', 'G']}, index = [3, 4, 5, 6, 7])

In [129]:
df1

   key1 values
0     0      A
1     1      B
2     2      C
3     3      D
4     4      E

In [130]:
df2

   key1 values
3     3      C
4     4      D
5     5      E
6     6      F
7     7      G

In [131]:
pd.concat([df1, df2])

   key1 values
0     0      A
1     1      B
2     2      C
3     3      D
4     4      E
3     3      C
4     4      D
5     5      E
6     6      F
7     7      G

In [133]:
pd.concat([df1, df2])

   key1 values
0     0      A
1     1      B
2     2      C
3     3      D
4     4      E
3     3      C
4     4      D
5     5      E
6     6      F
7     7      G

In [134]:
pd.concat([df1, df2], ignore_index = True)

   key1 values
0     0      A
1     1      B
2     2      C
3     3      D
4     4      E
5     3      C
6     4      D
7     5      E
8     6      F
9     7      G

In [135]:
pd.concat([df1, df2], axis = 1)

   key1 values  key1 values
0   0.0      A   NaN    NaN
1   1.0      B   NaN    NaN
2   2.0      C   NaN    NaN
3   3.0      D   3.0      C
4   4.0      E   4.0      D
5   NaN    NaN   5.0      E
6   NaN    NaN   6.0      F
7   NaN    NaN   7.0      G

In [136]:
df3 = pd.DataFrame({'a' : ['a0', 'a1', 'a2', 'a3'], 'b' : ['b0', 'b1', 'b2', 'b3'], 'c' : ['c0', 'c1', 'c2', 'c3']}, index = [0, 1, 2, 3])
df4 = pd.DataFrame({'a' : ['a2', 'a3', 'a4', 'a5'], 'c' : ['c2', 'c3', 'c4', 'c5'], 'd' : ['d2', 'd3', 'd4', 'd5']}, index = [2, 3, 4, 5])

In [137]:
df3

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [138]:
df4

    a   c   d
2  a2  c2  d2
3  a3  c3  d3
4  a4  c4  d4
5  a5  c5  d5

In [139]:
pd.concat([df3, df4], axis = 0)

    a    b   c    d
0  a0   b0  c0  NaN
1  a1   b1  c1  NaN
2  a2   b2  c2  NaN
3  a3   b3  c3  NaN
2  a2  NaN  c2   d2
3  a3  NaN  c3   d3
4  a4  NaN  c4   d4
5  a5  NaN  c5   d5

In [141]:
pd.concat([df3, df4], axis = 1)

     a    b    c    a    c    d
0   a0   b0   c0  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN
2   a2   b2   c2   a2   c2   d2
3   a3   b3   c3   a3   c3   d3
4  NaN  NaN  NaN   a4   c4   d4
5  NaN  NaN  NaN   a5   c5   d5

In [144]:
customer = pd.DataFrame({'고객ID' : np.arange(6), 
                         '이름' : ['철수', '영희', '길동', '영수', '수민', '동건'],
                         '나이' : [40, 20, 21, 30, 31, 18]})

In [146]:
orders = pd.DataFrame({
    '고객ID' : [1, 1, 2, 2, 2, 3, 3, 1, 4, 9],
    '상품명' : ['치약', '칫솔', '이어폰', '헤드셋', '수건', '생수', '수건', '치약', '생수', '케이스'],
    '수량' : [1, 2, 1, 1, 3, 2, 2, 3, 2, 1]
})

In [147]:
customer

   고객ID  이름  나이
0     0  철수  40
1     1  영희  20
2     2  길동  21
3     3  영수  30
4     4  수민  31
5     5  동건  18

In [148]:
orders

   고객ID  상품명  수량
0     1   치약   1
1     1   칫솔   2
2     2  이어폰   1
3     2  헤드셋   1
4     2   수건   3
5     3   생수   2
6     3   수건   2
7     1   치약   3
8     4   생수   2
9     9  케이스   1

In [150]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객ID    10 non-null     int64
 1   상품명     10 non-null     object
 2   수량      10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [151]:
pd.merge(customer, orders, on = '고객ID')

   고객ID  이름  나이  상품명  수량
0     1  영희  20   치약   1
1     1  영희  20   칫솔   2
2     1  영희  20   치약   3
3     2  길동  21  이어폰   1
4     2  길동  21  헤드셋   1
5     2  길동  21   수건   3
6     3  영수  30   생수   2
7     3  영수  30   수건   2
8     4  수민  31   생수   2

In [152]:
pd.merge(customer, orders, on = '고객ID', how = 'inner')

   고객ID  이름  나이  상품명  수량
0     1  영희  20   치약   1
1     1  영희  20   칫솔   2
2     1  영희  20   치약   3
3     2  길동  21  이어폰   1
4     2  길동  21  헤드셋   1
5     2  길동  21   수건   3
6     3  영수  30   생수   2
7     3  영수  30   수건   2
8     4  수민  31   생수   2

In [153]:
pd.merge(customer, orders, on = '고객ID', how = 'left')

    고객ID  이름  나이  상품명   수량
0      0  철수  40  NaN  NaN
1      1  영희  20   치약  1.0
2      1  영희  20   칫솔  2.0
3      1  영희  20   치약  3.0
4      2  길동  21  이어폰  1.0
5      2  길동  21  헤드셋  1.0
6      2  길동  21   수건  3.0
7      3  영수  30   생수  2.0
8      3  영수  30   수건  2.0
9      4  수민  31   생수  2.0
10     5  동건  18  NaN  NaN

In [154]:
pd.merge(customer, orders, on = '고객ID', how = 'right')

   고객ID   이름    나이  상품명  수량
0     1   영희  20.0   치약   1
1     1   영희  20.0   칫솔   2
2     2   길동  21.0  이어폰   1
3     2   길동  21.0  헤드셋   1
4     2   길동  21.0   수건   3
5     3   영수  30.0   생수   2
6     3   영수  30.0   수건   2
7     1   영희  20.0   치약   3
8     4   수민  31.0   생수   2
9     9  NaN   NaN  케이스   1

In [155]:
pd.merge(customer, orders, on = '고객ID', how = 'outer')

    고객ID   이름    나이  상품명   수량
0      0   철수  40.0  NaN  NaN
1      1   영희  20.0   치약  1.0
2      1   영희  20.0   칫솔  2.0
3      1   영희  20.0   치약  3.0
4      2   길동  21.0  이어폰  1.0
5      2   길동  21.0  헤드셋  1.0
6      2   길동  21.0   수건  3.0
7      3   영수  30.0   생수  2.0
8      3   영수  30.0   수건  2.0
9      4   수민  31.0   생수  2.0
10     5   동건  18.0  NaN  NaN
11     9  NaN   NaN  케이스  1.0

In [163]:
cust_order = pd.merge(customer, orders, on = '고객ID', how = 'right')

In [166]:
cust_order.groupby('상품명').sum()

     고객ID    이름    나이  수량
상품명
생수      7  영수수민  61.0   4
수건      5  길동영수  51.0   5
이어폰     2    길동  21.0   1
치약      2  영희영희  40.0   4
칫솔      1    영희  20.0   2
케이스     9     0   0.0   1
헤드셋     2    길동  21.0   1

In [169]:
cust_order.groupby('상품명').sum().sort_values('수량', ascending=False)

     고객ID    이름    나이  수량
상품명
수건      5  길동영수  51.0   5
생수      7  영수수민  61.0   4
치약      2  영희영희  40.0   4
칫솔      1    영희  20.0   2
이어폰     2    길동  21.0   1
케이스     9     0   0.0   1
헤드셋     2    길동  21.0   1