In [20]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [21]:
cust = pd.read_csv(r'C:\Users\leeji\Downloads\Chrome\study_csv\csv\sc_cust_info_txn_v1.5.csv')
cust

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,C,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,202006,20200630,10001,G,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,202006,20200630,10005,C,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,202006,20200630,10001,C,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,202006,20200630,10001,C,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [22]:
gender_group = cust.groupby("sex_type")
gender_group

In [23]:
gender_group.groups

{'F': [0, 2, 3, 5, 7, 9, 12, 13, 14, 16, 17, 19, 20, 21, 24, 25, 26, 40, 41, 43, 46, 47, 49, 51, 52, 55, 65, 69, 73, 75, 77, 79, 80, 81, 82, 85, 86, 90, 91, 93, 94, 95, 101, 105, 106, 111, 112, 116, 119, 120, 121, 127, 130, 131, 134, 135, 136, 137, 138, 142, 143, 147, 148, 149, 151, 152, 155, 156, 157, 159, 163, 164, 166, 167, 169, 173, 174, 176, 177, 181, 184, 190, 191, 193, 195, 197, 205, 206, 208, 210, 211, 213, 215, 216, 218, 221, 225, 230, 234, 235, ...], 'M': [4, 6, 8, 11, 15, 18, 22, 23, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39, 42, 44, 45, 48, 50, 53, 54, 56, 57, 58, 59, 60, 61, 63, 64, 67, 68, 70, 74, 76, 78, 84, 87, 88, 89, 96, 97, 98, 99, 100, 103, 104, 107, 108, 109, 110, 113, 115, 117, 122, 123, 124, 125, 126, 128, 132, 133, 139, 140, 141, 144, 145, 146, 150, 153, 154, 158, 160, 161, 162, 168, 170, 171, 172, 175, 178, 179, 180, 183, 185, 186, 187, 188, 189, 192, 194, 198, 199, 200, 201, ...], '_': [1, 10, 35, 62, 66, 71, 72, 83, 92, 102, 114, 118, 129, 165, 182, 196, 228, 232, 243, 288, 314, 317, 324, 393, 394, 451, 489, 496, 501, 502, 573, 611, 629, 658, 667, 669, 676, 683, 690, 701, 708, 717, 739, 751, 758, 773, 792, 816, 820, 821, 836, 851, 864, 895, 910, 935, 937, 942, 943, 946, 950, 971, 986, 991, 992, 1005, 1008, 1011, 1012, 1015, 1021, 1023, 1027, 1056, 1058, 1062, 1077, 1088, 1102, 1108, 1147, 1171, 1174, 1185, 1196, 1209, 1214, 1215, 1237, 1240, 1241, 1273, 1281, 1284, 1296, 1302, 1314, 1330, 1360, 1363, ...]}

In [24]:
gender_group.count()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
sex_type,,,,,,,,,,,,,,
F,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251
M,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998
_,681,681,681,681,681,681,681,681,681,681,681,681,681,681

In [25]:
gender_group.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [26]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9930 entries, 0 to 9929
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   base_ym             9930 non-null   int64
 1   dpro_tgt_perd_val   9930 non-null   int64
 2   cust_ctg_type       9930 non-null   int64
 3   cust_class          9930 non-null   object
 4   sex_type            9930 non-null   object
 5   age                 9930 non-null   object
 6   efct_svc_count      9930 non-null   int64
 7   dt_stop_yn          9930 non-null   object
 8   npay_yn             9930 non-null   object
 9   r3m_avg_bill_amt    9930 non-null   float64
 10  r3m_A_avg_arpu_amt  9930 non-null   float64
 11  r3m_B_avg_arpu_amt  9930 non-null   float64
 12  r6m_A_avg_arpu_amt  9930 non-null   float64
 13  r6m_B_avg_arpu_amt  9930 non-null   float64
 14  termination_yn      9930 non-null   object
dtypes: float64(5), int64(4), object(6)
memory usage: 1.1+ MB

In [27]:
cust.select_dtypes(['int64', 'float64'])

,base_ym,dpro_tgt_perd_val,cust_ctg_type,efct_svc_count,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt
0,202006,20200630,10001,0,2640.0000,792.000000,1584.0000,0.0,0.0000
1,202006,20200630,10001,1,300.0000,90.000000,180.0000,0.0,0.0000
2,202006,20200630,10001,1,16840.0000,2526.000000,6983.0000,0.0,6981.0000
3,202006,20200630,10001,1,15544.7334,2331.710010,6750.4666,0.0,6508.8000
4,202006,20200630,10001,1,4700.0000,0.000000,4502.0000,0.0,4507.7000
...,...,...,...,...,...,...,...,...,...
9925,202006,20200630,10001,1,1296.0999,194.414985,643.1001,0.0,852.5499
9926,202006,20200630,10001,1,13799.6666,2069.949990,10605.9266,0.0,10603.9266
9927,202006,20200630,10005,1,1396.2000,1206.000000,0.0000,1212.0,0.0000
9928,202006,20200630,10001,0,3140.0000,942.000000,1884.0000,0.0,0.0000
9929,202006,20200630,10001,1,2436.9000,365.535000,1839.9000,0.0,1919.7999

In [28]:
col = cust.select_dtypes(['int64', 'float64']).columns
col

Index(['base_ym', 'dpro_tgt_perd_val', 'cust_ctg_type', 'efct_svc_count',
       'r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt', 'r3m_B_avg_arpu_amt',
       'r6m_A_avg_arpu_amt', 'r6m_B_avg_arpu_amt'],
      dtype='object')

In [29]:
gender_group[['r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']].mean()

          r3m_avg_bill_amt  r3m_A_avg_arpu_amt
sex_type
F              9580.926307         1570.372299
M              9839.707339         1778.988878
_             40297.790077         4809.827390

In [30]:
gender_group[col].mean()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,efct_svc_count,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt
sex_type,,,,,,,,,
F,202006.0,20200630.0,10001.001882,1.098800,9580.926307,1570.372299,5283.876950,452.780488,4961.455810
M,202006.0,20200630.0,10001.004802,1.204882,9839.707339,1778.988878,5342.748791,641.426866,4851.027884
_,202006.0,20200630.0,10006.389134,6.462555,40297.790077,4809.827390,21057.412985,4854.788244,864.386867

In [31]:
gender_group.max()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
sex_type,,,,,,,,,,,,,,
F,202006,20200630,10005,_,_,9,Y,Y,7.979563e+04,5.500240e+04,5.710153e+04,2.302815e+04,48787.2333,Y
M,202006,20200630,10005,_,_,14,Y,Y,1.447397e+05,1.315815e+05,6.583656e+04,2.749282e+04,64947.0920,Y
_,202006,20200630,10010,_,_,905,Y,Y,1.281568e+07,1.188998e+06,7.689409e+06,1.208498e+06,18796.6266,Y

In [32]:
gender_group.max()[['r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']]

          r3m_avg_bill_amt  r3m_A_avg_arpu_amt
sex_type
F             7.979563e+04        5.500240e+04
M             1.447397e+05        1.315815e+05
_             1.281568e+07        1.188998e+06

In [33]:
gender_group.mean()[['r3m_avg_bill_amt', 'r3m_A_avg_arpu_amt']]

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
gender_group[['r3m_avg_bill_amt']].mean()

In [ ]:
cust.groupby('sex_type')[['r3m_avg_bill_amt']].mean()

In [ ]:
cust.groupby(['cust_class', 'sex_type'])[['r3m_avg_bill_amt']].mean()

In [ ]:
cust.groupby(['sex_type', 'cust_class'])[['r3m_avg_bill_amt']].mean()

In [ ]:
multi_group = cust.groupby(['cust_class', 'sex_type'])
multi_group[['r3m_avg_bill_amt']].mean()

In [ ]:
cust.groupby(['cust_class', 'sex_type'])[['r3m_avg_bill_amt']].mean().loc[[("C", "M"), ("D", "M")]]

In [34]:
cust.head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,cust_class,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,202006,20200630,10001,C,F,28,0,N,N,2640.0000,792.00000,1584.0000,0.0,0.0,Y
1,202006,20200630,10001,_,_,_,1,N,N,300.0000,90.00000,180.0000,0.0,0.0,Y
2,202006,20200630,10001,E,F,24,1,N,N,16840.0000,2526.00000,6983.0000,0.0,6981.0,N
3,202006,20200630,10001,F,F,32,1,N,N,15544.7334,2331.71001,6750.4666,0.0,6508.8,N
4,202006,20200630,10001,D,M,18,1,N,N,4700.0000,0.00000,4502.0000,0.0,4507.7,N

In [35]:
cust.set_index(['cust_class'])

,base_ym,dpro_tgt_perd_val,cust_ctg_type,sex_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
cust_class,,,,,,,,,,,,,,
C,202006,20200630,10001,F,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
_,202006,20200630,10001,_,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
E,202006,20200630,10001,F,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
F,202006,20200630,10001,F,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
D,202006,20200630,10001,M,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C,202006,20200630,10001,F,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
G,202006,20200630,10001,M,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
C,202006,20200630,10005,_,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
C,202006,20200630,10001,F,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
C,202006,20200630,10001,F,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [36]:
multi_cust = cust.set_index(['cust_class', 'sex_type'])
multi_cust

                     base_ym  dpro_tgt_perd_val  cust_ctg_type age  \
cust_class sex_type
C          F          202006           20200630          10001  28
_          _          202006           20200630          10001   _
E          F          202006           20200630          10001  24
F          F          202006           20200630          10001  32
D          M          202006           20200630          10001  18
...                      ...                ...            ...  ..
C          F          202006           20200630          10001  15
G          M          202006           20200630          10001  12
C          _          202006           20200630          10005   _
           F          202006           20200630          10001  40
           F          202006           20200630          10001  59

                     efct_svc_count dt_stop_yn npay_yn  r3m_avg_bill_amt  \
cust_class sex_type
C          F                      0          N       N         2640.0000
_          _                      1          N       N          300.0000
E          F                      1          N       N        16840.0000
F          F                      1          N       N        15544.7334
D          M                      1          N       N         4700.0000
...                             ...        ...     ...               ...
C          F                      1          N       Y         1296.0999
G          M                      1          N       N        13799.6666
C          _                      1          N       N         1396.2000
           F                      0          N       N         3140.0000
           F                      1          N       N         2436.9000

                     r3m_A_avg_arpu_amt  r3m_B_avg_arpu_amt  \
cust_class sex_type
C          F                 792.000000           1584.0000
_          _                  90.000000            180.0000
E          F                2526.000000           6983.0000
F          F                2331.710010           6750.4666
D          M                   0.000000           4502.0000
...                                 ...                 ...
C          F                 194.414985            643.1001
G          M                2069.949990          10605.9266
C          _                1206.000000              0.0000
           F                 942.000000           1884.0000
           F                 365.535000           1839.9000

                     r6m_A_avg_arpu_amt  r6m_B_avg_arpu_amt termination_yn
cust_class sex_type
C          F                        0.0              0.0000              Y
_          _                        0.0              0.0000              Y
E          F                        0.0           6981.0000              N
F          F                        0.0           6508.8000              N
D          M                        0.0           4507.7000              N
...                                 ...                 ...            ...
C          F                        0.0            852.5499              N
G          M                        0.0          10603.9266              N
C          _                     1212.0              0.0000              N
           F                        0.0              0.0000              Y
           F                        0.0           1919.7999              N

[9930 rows x 13 columns]

In [37]:
multi_cust.reset_index()

,cust_class,sex_type,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
0,C,F,202006,20200630,10001,28,0,N,N,2640.0000,792.000000,1584.0000,0.0,0.0000,Y
1,_,_,202006,20200630,10001,_,1,N,N,300.0000,90.000000,180.0000,0.0,0.0000,Y
2,E,F,202006,20200630,10001,24,1,N,N,16840.0000,2526.000000,6983.0000,0.0,6981.0000,N
3,F,F,202006,20200630,10001,32,1,N,N,15544.7334,2331.710010,6750.4666,0.0,6508.8000,N
4,D,M,202006,20200630,10001,18,1,N,N,4700.0000,0.000000,4502.0000,0.0,4507.7000,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9925,C,F,202006,20200630,10001,15,1,N,Y,1296.0999,194.414985,643.1001,0.0,852.5499,N
9926,G,M,202006,20200630,10001,12,1,N,N,13799.6666,2069.949990,10605.9266,0.0,10603.9266,N
9927,C,_,202006,20200630,10005,_,1,N,N,1396.2000,1206.000000,0.0000,1212.0,0.0000,N
9928,C,F,202006,20200630,10001,40,0,N,N,3140.0000,942.000000,1884.0000,0.0,0.0000,Y
9929,C,F,202006,20200630,10001,59,1,N,N,2436.9000,365.535000,1839.9000,0.0,1919.7999,N

In [38]:
multi_cust.head(3)

,,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
cust_class,sex_type,,,,,,,,,,,,,
C,F,202006,20200630,10001,28,0,N,N,2640.0,792.0,1584.0,0.0,0.0,Y
_,_,202006,20200630,10001,_,1,N,N,300.0,90.0,180.0,0.0,0.0,Y
E,F,202006,20200630,10001,24,1,N,N,16840.0,2526.0,6983.0,0.0,6981.0,N

In [39]:
multi_cust.groupby('cust_class').count().head()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
cust_class,,,,,,,,,,,,,
C,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092,2092
D,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250,2250
E,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269,1269
F,726,726,726,726,726,726,726,726,726,726,726,726,726
G,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051,2051

In [40]:
multi_cust.groupby('sex_type').count()

,base_ym,dpro_tgt_perd_val,cust_ctg_type,age,efct_svc_count,dt_stop_yn,npay_yn,r3m_avg_bill_amt,r3m_A_avg_arpu_amt,r3m_B_avg_arpu_amt,r6m_A_avg_arpu_amt,r6m_B_avg_arpu_amt,termination_yn
sex_type,,,,,,,,,,,,,
F,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251,4251
M,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998,4998
_,681,681,681,681,681,681,681,681,681,681,681,681,681

In [41]:
cust.set_index(['cust_class', 'sex_type']).groupby(['cust_class', 'sex_type']).count().head(9)

                     base_ym  dpro_tgt_perd_val  cust_ctg_type   age  \
cust_class sex_type
C          F             849                849            849   849
           M            1064               1064           1064  1064
           _             179                179            179   179
D          F            1097               1097           1097  1097
           M            1087               1087           1087  1087
           _              66                 66             66    66
E          F             639                639            639   639
           M             606                606            606   606
           _              24                 24             24    24

                     efct_svc_count  dt_stop_yn  npay_yn  r3m_avg_bill_amt  \
cust_class sex_type
C          F                    849         849      849               849
           M                   1064        1064     1064              1064
           _                    179         179      179               179
D          F                   1097        1097     1097              1097
           M                   1087        1087     1087              1087
           _                     66          66       66                66
E          F                    639         639      639               639
           M                    606         606      606               606
           _                     24          24       24                24

                     r3m_A_avg_arpu_amt  r3m_B_avg_arpu_amt  \
cust_class sex_type
C          F                        849                 849
           M                       1064                1064
           _                        179                 179
D          F                       1097                1097
           M                       1087                1087
           _                         66                  66
E          F                        639                 639
           M                        606                 606
           _                         24                  24

                     r6m_A_avg_arpu_amt  r6m_B_avg_arpu_amt  termination_yn
cust_class sex_type
C          F                        849                 849             849
           M                       1064                1064            1064
           _                        179                 179             179
D          F                       1097                1097            1097
           M                       1087                1087            1087
           _                         66                  66              66
E          F                        639                 639             639
           M                        606                 606             606
           _                         24                  24              24

In [42]:
cust.set_index(['cust_class', 'sex_type']).groupby(['cust_class', 'sex_type']).aggregate(['count']).head(9)

                    base_ym dpro_tgt_perd_val cust_ctg_type   age  \
                      count             count         count count
cust_class sex_type
C          F            849               849           849   849
           M           1064              1064          1064  1064
           _            179               179           179   179
D          F           1097              1097          1097  1097
           M           1087              1087          1087  1087
           _             66                66            66    66
E          F            639               639           639   639
           M            606               606           606   606
           _             24                24            24    24

                    efct_svc_count dt_stop_yn npay_yn r3m_avg_bill_amt  \
                             count      count   count            count
cust_class sex_type
C          F                   849        849     849              849
           M                  1064       1064    1064             1064
           _                   179        179     179              179
D          F                  1097       1097    1097             1097
           M                  1087       1087    1087             1087
           _                    66         66      66               66
E          F                   639        639     639              639
           M                   606        606     606              606
           _                    24         24      24               24

                    r3m_A_avg_arpu_amt r3m_B_avg_arpu_amt r6m_A_avg_arpu_amt  \
                                 count              count              count
cust_class sex_type
C          F                       849                849                849
           M                      1064               1064               1064
           _                       179                179                179
D          F                      1097               1097               1097
           M                      1087               1087               1087
           _                        66                 66                 66
E          F                       639                639                639
           M                       606                606                606
           _                        24                 24                 24

                    r6m_B_avg_arpu_amt termination_yn
                                 count          count
cust_class sex_type
C          F                       849            849
           M                      1064           1064
           _                       179            179
D          F                      1097           1097
           M                      1087           1087
           _                        66             66
E          F                       639            639
           M                       606            606
           _                        24             24

In [43]:
cust.set_index(['cust_class', 'sex_type']).groupby(['cust_class', 'sex_type']).aggregate(['min', 'max']).head(9)

                    base_ym         dpro_tgt_perd_val           cust_ctg_type  \
                        min     max               min       max           min
cust_class sex_type
C          F         202006  202006          20200630  20200630         10001
           M         202006  202006          20200630  20200630         10001
           _         202006  202006          20200630  20200630         10001
D          F         202006  202006          20200630  20200630         10001
           M         202006  202006          20200630  20200630         10001
           _         202006  202006          20200630  20200630         10005
E          F         202006  202006          20200630  20200630         10001
           M         202006  202006          20200630  20200630         10001
           _         202006  202006          20200630  20200630         10005

                           age     efct_svc_count      ... r3m_A_avg_arpu_amt  \
                       max min max            min max  ...                min
cust_class sex_type                                    ...
C          F         10005  10  99              0   3  ...                0.0
           M         10005  10  95              0   5  ...                0.0
           _         10005   _   _              0   5  ...               90.0
D          F         10005  10  91              0   6  ...                0.0
           M         10005  10   _              0   5  ...                0.0
           _         10005   _   _              0   5  ...              284.7
E          F         10001  12   _              0   6  ...                0.0
           M         10001  14  92              0   7  ...                0.0
           _         10005   _   _              0   5  ...              519.0

                                 r3m_B_avg_arpu_amt               \
                             max                min          max
cust_class sex_type
C          F          48101.6216                0.0  14434.01600
           M          14774.7336                0.0  13909.40000
           _          12389.3334                0.0  13760.71998
D          F          16653.6667                0.0  14382.00000
           M         131581.5333                0.0  19255.69998
           _          18686.9650                0.0  19397.80002
E          F          16373.3334                0.0  17532.89170
           M          37972.7998                0.0  43474.32550
           _           8696.0666                0.0   9865.06002

                    r6m_A_avg_arpu_amt             r6m_B_avg_arpu_amt  \
                                   min         max                min
cust_class sex_type
C          F                       0.0  10316.0334                0.0
           M                       0.0   9689.3332                0.0
           _                       0.0  19648.5002                0.0
D          F                       0.0   8964.5224                0.0
           M                       0.0  27492.8165                0.0
           _                       0.0  10242.7268                0.0
E          F                       0.0  13069.3334                0.0
           M                       0.0  13100.7334                0.0
           _                       0.0   8704.5000                0.0

                                termination_yn
                            max            min max
cust_class sex_type
C          F         14432.0160              N   Y
           M         14787.1166              N   Y
           _          8200.4640              N   Y
D          F         14467.3334              N   Y
           M         18133.6304              N   Y
           _             0.0000              N   Y
E          F         17306.4000              N   Y
           M         39802.3921              N   Y
           _             0.0000              N   Y

[9 rows x 26 columns]

In [45]:
sample = pd.DataFrame(
    {'고객ID': ['cust_1', 'cust_1', 'cust_1', 'cust_2', 'cust_2', 'cust_2', 'cust_3', 'cust_3', 'cust_3'],
     '상품코드': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
     '등급': ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
     '구매금액': [30, 10, 0, 40, 15, 30, 0, 0, 10],
     '나이': [15, 40, 33, 29, 6, 30, 54, 69, 38]
     }
)
sample

     고객ID 상품코드 등급  구매금액  나이
0  cust_1   p1  A    30  15
1  cust_1   p2  A    10  40
2  cust_1   p3  A     0  33
3  cust_2   p1  A    40  29
4  cust_2   p2  A    15   6
5  cust_2   p3  A    30  30
6  cust_3   p1  B     0  54
7  cust_3   p2  B     0  69
8  cust_3   p3  B    10  38

In [53]:
pd.pivot_table(data = sample[['고객ID', '구매금액', '나이']], index = '고객ID', aggfunc = 'mean')

             구매금액         나이
고객ID
cust_1  13.333333  29.333333
cust_2  28.333333  21.666667
cust_3   3.333333  53.666667

In [56]:
sample[['고객ID', '구매금액', '나이']].groupby('고객ID').mean()

             구매금액         나이
고객ID
cust_1  13.333333  29.333333
cust_2  28.333333  21.666667
cust_3   3.333333  53.666667

In [57]:
sample.pivot_table(index = '고객ID', columns = '상품코드', aggfunc = 'sum')

       구매금액          나이         등급
상품코드     p1  p2  p3  p1  p2  p3 p1 p2 p3
고객ID
cust_1   30  10   0  15  40  33  A  A  A
cust_2   40  15  30  29   6  30  A  A  A
cust_3    0   0  10  54  69  38  B  B  B